backend:
  name: github
  repo: luizfverissimo/birds-of-brazil-portfolio
  branch: main
  site_domain: https://birds-of-brazil-portfolio.vercel.app
media_folder: /public/img
site_url: https://birds-of-brazil-portfolio.vercel.app
display_url: https://birds-of-brazil-portfolio.vercel.app
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - label: 'Posts'
    name: 'posts'
    folder: 'content'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Species', name: 'species', widget: 'string', required: true }
      - { label: 'City', name: 'city', widget: 'string', required: true }
      - { label: 'State', name: 'state', widget: 'string', required: true }
      - {
          label: 'Region',
          name: 'region',
          widget: 'select',
          options: ['North', 'Northeast', 'Midwest', 'Southeast', 'South'],
          required: true
        }
      - {
          label: 'Photo taken date',
          name: 'date',
          widget: 'date',
          format: 'MM/DD/YYYY',
          required: true
        }
      - {
          label: 'Featured Image',
          name: 'img',
          widget: 'image',
          required: true,
          media_folder: /public/img
        }
